In [ ]:
import numpy as n

arr=n.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [1]:
import numpy as np

lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst * 2)   # duplicates list
print(arr * 2)   # math multiplication
print(arr + 10)
print(arr ** 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]
[11 12 13]
[1 4 9]


In [25]:
arr = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]])

print(arr.shape)    #rows and columns
print(arr.ndim)     #dimension
print(arr.size)     #total elements

(2, 3, 3)
3
18


In [11]:
np.zeros(5)        # [0. 0. 0. 0. 0.]
np.ones(3)         # [1. 1. 1.]
np.arange(1, 6)    # [1 2 3 4 5]
np.linspace(0, 1, 5)  # evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
a = np.array([10, 20, 30, 40])

print(a[0])     # 10
print(a[-2:0:1])
print(a[::-1])    # 40

10
[]
[40 30 20 10]


In [21]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a[0, 1])  # 2
print(a[:, 1])  # column
print(a[1, :])  # row

2
[2 5]
[4 5 6]


In [22]:
a = np.array([1, 2, 3])

print(a + 1)
print(a * 2)
print(a ** 2)

[2 3 4]
[2 4 6]
[1 4 9]


In [38]:
np.sqrt(a)
np.log(a)
np.exp(a)

array([2.71828183e+000, 5.83461743e+014, 1.38312148e+184, 2.61951732e+053])

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])

b = arr.reshape(6, 3)
print(b)

c = b.flatten()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [24]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.sum(axis=0))  # column-wise
print(a.sum(axis=1))  # row-wise

21
3.5
6
1
[5 7 9]
[ 6 15]


In [34]:
print(np.random.rand(3))       # uniform
print(np.random.randn(3))      # normal
print(np.random.randint(999, 10000, size=5))

[0.67884568 0.32734105 0.73539535]
[ 0.32247609 -0.2052265   0.37376181]
[5156 1316 5147 4780 4600]


Boolean masking 

In [ ]:
a = np.array([1,-1,34,424,123])

mask = a > 15

print(a[mask])

[ 34 424 123]


Hadling missing/Invalid data

In [2]:
data = np.array([1, 2, np.nan, 4])

print(np.isnan(data))
print(data[~np.isnan(data)])

[False False  True False]
[1. 2. 4.]


In [43]:
a1 = np.array([[1, 2, 3],
            [4, 5, 6]])
a2=np.array([[11, 22, 33],
            [44, 55, 66]])

print(np.vstack([a1, a2]))

print(np.hstack([a1, a2]))

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]


In [64]:
a1=np.arange(1,11)
a1.reshape(5,2)
print(np.split(a1,2))
print(np.split(a1,[0,2]))
print(np.hsplit(a1,1))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([], dtype=int64), array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10])]
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])]


Function    Works on	    Meaning

split	    1D or rows	    General split

hsplit	    columns	        Column-wise split

vsplit	    rows	        Row-wise split

In [65]:
import numpy as np

# ------------------------------------
# 1️⃣ ORIGINAL DATA (1D array)
# ------------------------------------
a = np.array([10, 20, 30, 40])

print("Original array:", a)
print()

# ------------------------------------
# 2️⃣ SPLIT INTO EQUAL PARTS
# ------------------------------------
equal_split = np.split(a, 2)

print("Equal split into 2 parts:")
print(equal_split)
print()

# ------------------------------------
# 3️⃣ POSITION-BASED SPLIT
# Cut BEFORE index 1 and BEFORE index 3
# ------------------------------------
position_split = np.split(a, [1, 3])

print("Position-based split at indexes [1, 3]:")
print(position_split)
print()

# ============================================================
# NOW 2D ARRAY (TABLE-LIKE DATA)
# ============================================================

# ------------------------------------
# 4️⃣ 2D ARRAY (ROWS × COLUMNS)
# ------------------------------------
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("2D Array:")
print(A)
print()

# ------------------------------------
# 5️⃣ HORIZONTAL SPLIT (COLUMNS)
# Equal split into 2 parts
# ------------------------------------
h_equal = np.hsplit(A, 2)

print("hsplit into 2 equal column parts:")
for part in h_equal:
    print(part)
print()

# ------------------------------------
# 6️⃣ POSITION-BASED HSPLIT
# Cut BEFORE column 1 and BEFORE column 3
# ------------------------------------
h_position = np.hsplit(A, [1, 3])

print("hsplit with positions [1, 3]:")
for part in h_position:
    print(part)
print()

# ------------------------------------
# 7️⃣ REAL-LIFE STYLE DATA
# ID | Age | Salary | Label
# ------------------------------------
data = np.array([
    [101, 25, 50000, 1],
    [102, 30, 60000, 0]
])

print("Real-life data:")
print(data)
print()

# ------------------------------------
# 8️⃣ SPLIT REAL DATA USING POSITIONS
# ------------------------------------
id_col, features, label = np.hsplit(data, [1, 3])

print("ID column:")
print(id_col)
print()

print("Features (Age, Salary):")
print(features)
print()

print("Label:")
print(label)


Original array: [10 20 30 40]

Equal split into 2 parts:
[array([10, 20]), array([30, 40])]

Position-based split at indexes [1, 3]:
[array([10]), array([20, 30]), array([40])]

2D Array:
[[1 2 3 4]
 [5 6 7 8]]

hsplit into 2 equal column parts:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]

hsplit with positions [1, 3]:
[[1]
 [5]]
[[2 3]
 [6 7]]
[[4]
 [8]]

Real-life data:
[[  101    25 50000     1]
 [  102    30 60000     0]]

ID column:
[[101]
 [102]]

Features (Age, Salary):
[[   25 50000]
 [   30 60000]]

Label:
[[1]
 [0]]
